In [1]:
import pandas as pd
from prophet import Prophet

/Users/buithianhdao/Library/Python/3.10/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Importing plotly failed. Interactive plots will not work.

In [2]:
df = pd.read_csv("../../sales.csv")

In [3]:
df

            Date     Revenue        COGS
0     2012-07-04  5123547.94  3982991.19
1     2012-07-05  2751773.45  2150580.23
2     2012-07-06  3054029.42  2517632.84
3     2012-07-07  2667930.94  2108246.62
4     2012-07-08  2360851.90  1808622.79
...          ...         ...         ...
3828  2022-12-27  2100553.66  2184872.24
3829  2022-12-28  3448729.20  3513621.00
3830  2022-12-29  3083944.33  3170787.10
3831  2022-12-30  2884668.76  3022292.15
3832  2022-12-31  2383037.48  2279288.13

[3833 rows x 3 columns]

In [4]:
df_rev_prophet = df[['Date', 'Revenue']].rename(columns={'Date': 'ds', 'Revenue': 'y'})

In [5]:
df_rev_prophet

              ds           y
0     2012-07-04  5123547.94
1     2012-07-05  2751773.45
2     2012-07-06  3054029.42
3     2012-07-07  2667930.94
4     2012-07-08  2360851.90
...          ...         ...
3828  2022-12-27  2100553.66
3829  2022-12-28  3448729.20
3830  2022-12-29  3083944.33
3831  2022-12-30  2884668.76
3832  2022-12-31  2383037.48

[3833 rows x 2 columns]

In [6]:
m = Prophet(
    growth='linear',                  # or 'logistic' if revenue has a ceiling
    yearly_seasonality=True,
    weekly_seasonality=True,
    seasonality_mode='multiplicative', # crucial for revenue — variance grows with level
    changepoint_prior_scale=0.05      # controls trend flexibility, tune this
)

In [7]:
m.fit(df_rev_prophet)

13:29:24 - cmdstanpy - INFO - Chain [1] start processing
13:29:25 - cmdstanpy - INFO - Chain [1] done processing

In [8]:
future = pd.read_csv('../../sample_submission.csv')[['Date']].rename(columns={'Date': 'ds'})

In [9]:
forecast = m.predict(future)

In [10]:
forecast

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,additive_terms,additive_terms_lower,additive_terms_upper,yhat
0,2023-01-01,3.148152e+06,-1.914844e+05,4.543143e+06,3.148152e+06,3.148152e+06,-0.366765,-0.366765,-0.366765,-0.051190,-0.051190,-0.051190,-0.315575,-0.315575,-0.315575,0.0,0.0,0.0,1.993519e+06
1,2023-01-02,3.148446e+06,-2.189570e+05,4.448099e+06,3.148446e+06,3.148446e+06,-0.319641,-0.319641,-0.319641,0.003378,0.003378,0.003378,-0.323019,-0.323019,-0.323019,0.0,0.0,0.0,2.142072e+06
2,2023-01-03,3.148740e+06,-1.462975e+05,4.668152e+06,3.148740e+06,3.148740e+06,-0.287931,-0.287931,-0.287931,0.043970,0.043970,0.043970,-0.331901,-0.331901,-0.331901,0.0,0.0,0.0,2.242120e+06
3,2023-01-04,3.149034e+06,1.767182e+05,4.686528e+06,3.149034e+06,3.149034e+06,-0.249700,-0.249700,-0.249700,0.092323,0.092323,0.092323,-0.342023,-0.342023,-0.342023,0.0,0.0,0.0,2.362719e+06
4,2023-01-05,3.149328e+06,-5.441091e+04,4.731648e+06,3.149328e+06,3.149328e+06,-0.297357,-0.297357,-0.297357,0.055804,0.055804,0.055804,-0.353161,-0.353161,-0.353161,0.0,0.0,0.0,2.212853e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,2024-06-27,3.307779e+06,1.635587e+06,6.354725e+06,2.901865e+06,3.746876e+06,0.237356,0.237356,0.237356,0.055804,0.055804,0.055804,0.181552,0.181552,0.181552,0.0,0.0,0.0,4.092899e+06
544,2024-06-28,3.308073e+06,1.273316e+06,5.869310e+06,2.901716e+06,3.748367e+06,0.099253,0.099253,0.099253,-0.055895,-0.055895,-0.055895,0.155148,0.155148,0.155148,0.0,0.0,0.0,3.636410e+06
545,2024-06-29,3.308367e+06,1.149275e+06,5.887235e+06,2.901567e+06,3.749858e+06,0.042741,0.042741,0.042741,-0.088388,-0.088388,-0.088388,0.131130,0.131130,0.131130,0.0,0.0,0.0,3.449771e+06
546,2024-06-30,3.308661e+06,1.139702e+06,5.736525e+06,2.900068e+06,3.751349e+06,0.058522,0.058522,0.058522,-0.051190,-0.051190,-0.051190,0.109712,0.109712,0.109712,0.0,0.0,0.0,3.502289e+06
547,2024-07-01,3.308955e+06,1.353197e+06,6.058840e+06,2.898426e+06,3.752841e+06,0.094442,0.094442,0.094442,0.003378,0.003378,0.003378,0.091064,0.091064,0.091064,0.0,0.0,0.0,3.621459e+06

In [ ]:
ans = pd.read_csv('../../sample_submission.csv')

In [20]:
ans['Revenue'] = forecast['yhat'].values

# COGS

In [22]:
df_cogs_prophet = df[['Date', 'COGS']].rename(columns={'Date': 'ds', 'COGS': 'y'})

In [25]:
m = Prophet(
    growth='linear',                  # or 'logistic' if revenue has a ceiling
    yearly_seasonality=True,
    weekly_seasonality=True,
    seasonality_mode='multiplicative', # crucial for revenue — variance grows with level
    changepoint_prior_scale=0.05      # controls trend flexibility, tune this
)

In [ ]:
m.fit(df_rev_prophet)

10:45:55 - cmdstanpy - INFO - Chain [1] start processing
10:45:55 - cmdstanpy - INFO - Chain [1] done processing

In [ ]:
future = pd.read_csv('../../sample_submission.csv')[['Date']].rename(columns={'Date': 'ds'})

In [ ]:
forecast = m.predict(future)

In [ ]:
from prophet.diagnostics import cross_validation

df_cv = cross_validation(
    m,
    initial='365 days',
    period='30 days',
    horizon='90 days'
)

Seasonality has period of 365.25 days which is larger than initial window. Consider increasing initial.
  0%|          | 0/113 [00:00<?, ?it/s]10:49:59 - cmdstanpy - INFO - Chain [1] start processing
10:49:59 - cmdstanpy - INFO - Chain [1] done processing
  1%|          | 1/113 [00:00<00:14,  7.69it/s]10:49:59 - cmdstanpy - INFO - Chain [1] start processing
10:49:59 - cmdstanpy - INFO - Chain [1] done processing
10:49:59 - cmdstanpy - INFO - Chain [1] start processing
10:49:59 - cmdstanpy - INFO - Chain [1] done processing
  3%|▎         | 3/113 [00:00<00:09, 11.82it/s]10:49:59 - cmdstanpy - INFO - Chain [1] start processing
10:49:59 - cmdstanpy - INFO - Chain [1] done processing
10:49:59 - cmdstanpy - INFO - Chain [1] start processing
10:49:59 - cmdstanpy - INFO - Chain [1] done processing
  4%|▍         | 5/113 [00:00<00:08, 12.49it/s]10:49:59 - cmdstanpy - INFO - Chain [1] start processing
10:49:59 - cmdstanpy - INFO - Chain [1] done processing
10:49:59 - cmdstanpy - INFO - Chain [1] start processing
10:49:59 - cmdstanpy - INFO - Chain [1] done processing
  6%|▌         | 7/113 [00:00<00:08, 12.29it/s]10:49:59 - cmdstanpy - INFO - Chain [1] start processing
10:49:59 - cmdstanpy - INFO - Chain [1] done processing
10:49:59 - cmdstanpy - INFO - Chain [1] start processing
10:49:59 - cmdstanpy - INFO - Chain [1] done processing
  8%|▊         | 9/113 [00:00<00:08, 11.77it/s]10:49:59 - cmdstanpy - INFO - Chain [1] start processing
10:49:59 - cmdstanpy - INFO - Chain [1] done processing
10:49:59 - cmdstanpy - INFO - Chain [1] start processing
10:49:59 - cmdstanpy - INFO - Chain [1] done processing
 10%|▉         | 11/113 [00:00<00:08, 11.81it/s]10:50:00 - cmdstanpy - INFO - Chain [1] start processing
10:50:00 - cmdstanpy - INFO - Chain [1] done processing
10:50:00 - cmdstanpy - INFO - Chain [1] start processing
10:50:00 - cmdstanpy - INFO - Chain [1] done processing
 12%|█▏        | 13/113 [00:01<00:08, 11.30it/s]10:50:00 - cmdstanpy - INFO - Chain [1] start processing
10:50:00 - cmdstanpy - INFO - Chain [1] done processing
10:50:00 - cmdstanpy - INFO - Chain [1] start processing
10:50:00 - cmdstanpy - INFO - Chain [1] done processing
 13%|█▎        | 15/113 [00:01<00:09, 10.75it/s]10:50:00 - cmdstanpy - INFO - Chain [1] start processing
10:50:00 - cmdstanpy - INFO - Chain [1] done processing
10:50:00 - cmdstanpy - INFO - Chain [1] start processing
10:50:00 - cmdstanpy - INFO - Chain [1] done processing
 15%|█▌        | 17/113 [00:01<00:09, 10.36it/s]10:50:00 - cmdstanpy - INFO - Chain [1] start processing
10:50:00 - cmdstanpy - INFO - Chain [1] done processing
10:50:00 - cmdstanpy - INFO - Chain [1] start processing
10:50:00 - cmdstanpy - INFO - Chain [1] done processing
 17%|█▋        | 19/113 [00:01<00:09, 10.02it/s]10:50:00 - cmdstanpy - INFO - Chain [1] start processing
10:50:00 - cmdstanpy - INFO - Chain [1] done processing
10:50:01 - cmdstanpy - INFO - Chain [1] start processing
10:50:01 - cmdstanpy - INFO - Chain [1] done processing
 19%|█▊        | 21/113 [00:02<00:10,  9.09it/s]10:50:01 - cmdstanpy - INFO - Chain [1] start processing
10:50:01 - cmdstanpy - INFO - Chain [1] done processing
10:50:01 - cmdstanpy - INFO - Chain [1] start processing
10:50:01 - cmdstanpy - INFO - Chain [1] done processing
 20%|██        | 23/113 [00:02<00:09,  9.47it/s]10:50:01 - cmdstanpy - INFO - Chain [1] start processing
10:50:01 - cmdstanpy - INFO - Chain [1] done processing
 21%|██        | 24/113 [00:02<00:09,  9.30it/s]10:50:01 - cmdstanpy - INFO - Chain [1] start processing
10:50:01 - cmdstanpy - INFO - Chain [1] done processing
 22%|██▏       | 25/113 [00:02<00:09,  9.31it/s]10:50:01 - cmdstanpy - INFO - Chain [1] start processing
10:50:01 - cmdstanpy - INFO - Chain [1] done processing
 23%|██▎       | 26/113 [00:02<00:09,  9.10it/s]10:50:01 - cmdstanpy - INFO - Chain [1] start processing
10:50:01 - cmdstanpy - INFO - Chain [1] done processing
 24%|██▍       | 27/113 [00:02<00:09,  9.23it/s]10:50:01 - cmdstanpy - INFO - Chain [1] start processing
10:50:01 - cmdstanpy - INFO - Chain [1] done processing
 25%|██▍       | 28/113 [00:02<00:09,  9.12it/s]10:50:01 - cmdstanpy - INFO - Chain [1] start processing
10:50:01 - cmdstanpy - INFO - Chain [1] done processing
 26%|██▌       | 29/113 [00:02<00:09,  8.96it/s]10:50:02 - cmdstanpy - INFO - Chain [1] start processing
10:50:02 - cmdstanpy - INFO - Chain [1] done processing
 27%|██▋       | 30/113 [00:03<00:09,  8.85it/s]10:50:02 - cmdstanpy - INFO - Chain [1] start processing
10:50:02 - cmdstanpy - INFO - Chain [1] done processing
 27%|██▋       | 31/113 [00:03<00:09,  8.87it/s]10:50:02 - cmdstanpy - INFO - Chain [1] start processing
10:50:02 - cmdstanpy - INFO - Chain [1] done processing
 28%|██▊       | 32/113 [00:03<00:09,  8.81it/s]10:50:02 - cmdstanpy - INFO - Chain [1] start processing
10:50:02 - cmdstanpy - INFO - Chain [1] done processing
 29%|██▉       | 33/113 [00:03<00:09,  8.53it/s]10:50:02 - cmdstanpy - INFO - Chain [1] start processing
10:50:02 - cmdstanpy - INFO - Chain [1] done processing
 30%|███       | 34/113 [00:03<00:09,  8.60it/s]10:50:02 - cmdstanpy - INFO - Chain [1] start processing
10:50:02 - cmdstanpy - INFO - Chain [1] done processing
 31%|███       | 35/113 [00:03<00:09,  8.63it/s]10:50:02 - cmdstanpy - INFO - Chain [1] start processing
10:50:02 - cmdstanpy - INFO - Chain [1] done processing
 32%|███▏      | 36/113 [00:03<00:09,  8.44it/s]10:50:02 - cmdstanpy - INFO - Chain [1] start processing
10:50:02 - cmdstanpy - INFO - Chain [1] done processing
 33%|███▎      | 37/113 [00:03<00:09,  7.89it/s]10:50:02 - cmdstanpy - INFO - Chain [1] start processing
10:50:03 - cmdstanpy - INFO - Chain [1] done processing
 34%|███▎      | 38/113 [00:03<00:09,  7.93it/s]10:50:03 - cmdstanpy - INFO - Chain [1] start processing
10:50:03 - cmdstanpy - INFO - Chain [1] done processing
 35%|███▍      | 39/113 [00:04<00:09,  7.91it/s]10:50:03 - cmdstanpy - INFO - Chain [1] start processing
10:50:03 - cmdstanpy - INFO - Chain [1] done processing
 35%|███▌      | 40/113 [00:04<00:09,  7.44it/s]10:50:03 - cmdstanpy - INFO - Chain [1] start processing
10:50:03 - cmdstanpy - INFO - Chain [1] done processing
 36%|███▋      | 41/113 [00:04<00:09,  7.22it/s]10:50:03 - cmdstanpy - INFO - Chain [1] start processing
10:50:03 - cmdstanpy - INFO - Chain [1] done processing
 37%|███▋      | 42/113 [00:04<00:10,  6.88it/s]10:50:03 - cmdstanpy - INFO - Chain [1] start processing
10:50:03 - cmdstanpy - INFO - Chain [1] done processing
 38%|███▊      | 43/113 [00:04<00:10,  6.99it/s]10:50:03 - cmdstanpy - INFO - Chain [1] start processing
10:50:03 - cmdstanpy - INFO - Chain [1] done processing
 39%|███▉      | 44/113 [00:04<00:09,  7.26it/s]10:50:04 - cmdstanpy - INFO - Chain [1] start processing
10:50:04 - cmdstanpy - INFO - Chain [1] done processing
 40%|███▉      | 45/113 [00:05<00:10,  6.66it/s]10:50:04 - cmdstanpy - INFO - Chain [1] start processing
10:50:04 - cmdstanpy - INFO - Chain [1] done processing
 41%|████      | 46/113 [00:05<00:10,  6.56it/s]10:50:04 - cmdstanpy - INFO - Chain [1] start processing
10:50:04 - cmdstanpy - INFO - Chain [1] done processing
 42%|████▏     | 47/113 [00:05<00:09,  6.66it/s]10:50:04 - cmdstanpy - INFO - Chain [1] start processing
10:50:04 - cmdstanpy - INFO - Chain [1] done processing
 42%|████▏     | 48/113 [00:05<00:09,  6.58it/s]10:50:04 - cmdstanpy - INFO - Chain [1] start processing
10:50:04 - cmdstanpy - INFO - Chain [1] done processing
 43%|████▎     | 49/113 [00:05<00:09,  6.43it/s]10:50:04 - cmdstanpy - INFO - Chain [1] start processing
10:50:04 - cmdstanpy - INFO - Chain [1] done processing
 44%|████▍     | 50/113 [00:05<00:09,  6.63it/s]10:50:04 - cmdstanpy - INFO - Chain [1] start processing
10:50:04 - cmdstanpy - INFO - Chain [1] done processing
 45%|████▌     | 51/113 [00:05<00:09,  6.60it/s]10:50:05 - cmdstanpy - INFO - Chain [1] start processing
10:50:05 - cmdstanpy - INFO - Chain [1] done processing
 46%|████▌     | 52/113 [00:06<00:09,  6.52it/s]10:50:05 - cmdstanpy - INFO - Chain [1] start processing
10:50:05 - cmdstanpy - INFO - Chain [1] done processing
 47%|████▋     | 53/113 [00:06<00:09,  6.36it/s]10:50:05 - cmdstanpy - INFO - Chain [1] start processing
10:50:05 - cmdstanpy - INFO - Chain [1] done processing
 48%|████▊     | 54/113 [00:06<00:09,  6.44it/s]10:50:05 - cmdstanpy - INFO - Chain [1] start processing
10:50:05 - cmdstanpy - INFO - Chain [1] done processing
 49%|████▊     | 55/113 [00:06<00:09,  6.20it/s]10:50:05 - cmdstanpy - INFO - Chain [1] start processing
10:50:05 - cmdstanpy - INFO - Chain [1] done processing
 50%|████▉     | 56/113 [00:06<00:09,  6.18it/s]10:50:05 - cmdstanpy - INFO - Chain [1] start processing
10:50:05 - cmdstanpy - INFO - Chain [1] done processing
 50%|█████     | 57/113 [00:06<00:09,  6.18it/s]10:50:06 - cmdstanpy - INFO - Chain [1] start processing
10:50:06 - cmdstanpy - INFO - Chain [1] done processing
 51%|█████▏    | 58/113 [00:07<00:08,  6.12it/s]10:50:06 - cmdstanpy - INFO - Chain [1] start processing
10:50:06 - cmdstanpy - INFO - Chain [1] done processing
 52%|█████▏    | 59/113 [00:07<00:09,  5.88it/s]10:50:06 - cmdstanpy - INFO - Chain [1] start processing
10:50:06 - cmdstanpy - INFO - Chain [1] done processing
 53%|█████▎    | 60/113 [00:07<00:08,  5.94it/s]10:50:06 - cmdstanpy - INFO - Chain [1] start processing
10:50:06 - cmdstanpy - INFO - Chain [1] done processing
 54%|█████▍    | 61/113 [00:07<00:08,  5.98it/s]10:50:06 - cmdstanpy - INFO - Chain [1] start processing
10:50:06 - cmdstanpy - INFO - Chain [1] done processing
 55%|█████▍    | 62/113 [00:07<00:08,  5.81it/s]10:50:06 - cmdstanpy - INFO - Chain [1] start processing
10:50:07 - cmdstanpy - INFO - Chain [1] done processing
 56%|█████▌    | 63/113 [00:07<00:09,  5.53it/s]10:50:07 - cmdstanpy - INFO - Chain [1] start processing
10:50:07 - cmdstanpy - INFO - Chain [1] done processing
 57%|█████▋    | 64/113 [00:08<00:09,  5.16it/s]10:50:07 - cmdstanpy - INFO - Chain [1] start processing
10:50:07 - cmdstanpy - INFO - Chain [1] done processing
 58%|█████▊    | 65/113 [00:08<00:09,  5.16it/s]10:50:07 - cmdstanpy - INFO - Chain [1] start processing
10:50:07 - cmdstanpy - INFO - Chain [1] done processing
 58%|█████▊    | 66/113 [00:08<00:08,  5.28it/s]10:50:07 - cmdstanpy - INFO - Chain [1] start processing
10:50:07 - cmdstanpy - INFO - Chain [1] done processing
 59%|█████▉    | 67/113 [00:08<00:10,  4.41it/s]10:50:08 - cmdstanpy - INFO - Chain [1] start processing
10:50:08 - cmdstanpy - INFO - Chain [1] done processing
 60%|██████    | 68/113 [00:09<00:10,  4.19it/s]10:50:08 - cmdstanpy - INFO - Chain [1] start processing
10:50:08 - cmdstanpy - INFO - Chain [1] done processing
 61%|██████    | 69/113 [00:09<00:10,  4.34it/s]10:50:08 - cmdstanpy - INFO - Chain [1] start processing
10:50:08 - cmdstanpy - INFO - Chain [1] done processing
 62%|██████▏   | 70/113 [00:09<00:09,  4.67it/s]10:50:08 - cmdstanpy - INFO - Chain [1] start processing
10:50:08 - cmdstanpy - INFO - Chain [1] done processing
 63%|██████▎   | 71/113 [00:09<00:08,  4.68it/s]10:50:08 - cmdstanpy - INFO - Chain [1] start processing
10:50:09 - cmdstanpy - INFO - Chain [1] done processing
 64%|██████▎   | 72/113 [00:10<00:09,  4.21it/s]10:50:09 - cmdstanpy - INFO - Chain [1] start processing
10:50:09 - cmdstanpy - INFO - Chain [1] done processing
 65%|██████▍   | 73/113 [00:10<00:09,  4.04it/s]10:50:09 - cmdstanpy - INFO - Chain [1] start processing
10:50:09 - cmdstanpy - INFO - Chain [1] done processing
 65%|██████▌   | 74/113 [00:10<00:09,  4.23it/s]10:50:09 - cmdstanpy - INFO - Chain [1] start processing
10:50:09 - cmdstanpy - INFO - Chain [1] done processing
 66%|██████▋   | 75/113 [00:10<00:09,  4.00it/s]10:50:09 - cmdstanpy - INFO - Chain [1] start processing
10:50:10 - cmdstanpy - INFO - Chain [1] done processing
 67%|██████▋   | 76/113 [00:11<00:09,  4.00it/s]10:50:10 - cmdstanpy - INFO - Chain [1] start processing
10:50:10 - cmdstanpy - INFO - Chain [1] done processing
 68%|██████▊   | 77/113 [00:11<00:09,  4.00it/s]10:50:10 - cmdstanpy - INFO - Chain [1] start processing
10:50:10 - cmdstanpy - INFO - Chain [1] done processing
 69%|██████▉   | 78/113 [00:11<00:08,  4.20it/s]10:50:10 - cmdstanpy - INFO - Chain [1] start processing
10:50:10 - cmdstanpy - INFO - Chain [1] done processing
 70%|██████▉   | 79/113 [00:11<00:08,  4.22it/s]10:50:10 - cmdstanpy - INFO - Chain [1] start processing
10:50:11 - cmdstanpy - INFO - Chain [1] done processing
 71%|███████   | 80/113 [00:11<00:07,  4.22it/s]10:50:11 - cmdstanpy - INFO - Chain [1] start processing
10:50:11 - cmdstanpy - INFO - Chain [1] done processing
 72%|███████▏  | 81/113 [00:12<00:08,  3.91it/s]10:50:11 - cmdstanpy - INFO - Chain [1] start processing
10:50:11 - cmdstanpy - INFO - Chain [1] done processing
 73%|███████▎  | 82/113 [00:12<00:07,  3.96it/s]10:50:11 - cmdstanpy - INFO - Chain [1] start processing
10:50:11 - cmdstanpy - INFO - Chain [1] done processing
 73%|███████▎  | 83/113 [00:12<00:07,  3.89it/s]10:50:11 - cmdstanpy - INFO - Chain [1] start processing
10:50:12 - cmdstanpy - INFO - Chain [1] done processing
 74%|███████▍  | 84/113 [00:13<00:07,  3.96it/s]10:50:12 - cmdstanpy - INFO - Chain [1] start processing
10:50:12 - cmdstanpy - INFO - Chain [1] done processing
 75%|███████▌  | 85/113 [00:13<00:06,  4.10it/s]10:50:12 - cmdstanpy - INFO - Chain [1] start processing
10:50:12 - cmdstanpy - INFO - Chain [1] done processing
 76%|███████▌  | 86/113 [00:13<00:06,  4.31it/s]10:50:12 - cmdstanpy - INFO - Chain [1] start processing
10:50:12 - cmdstanpy - INFO - Chain [1] done processing
 77%|███████▋  | 87/113 [00:13<00:06,  4.31it/s]10:50:12 - cmdstanpy - INFO - Chain [1] start processing
10:50:13 - cmdstanpy - INFO - Chain [1] done processing
 78%|███████▊  | 88/113 [00:13<00:06,  4.14it/s]10:50:13 - cmdstanpy - INFO - Chain [1] start processing
10:50:13 - cmdstanpy - INFO - Chain [1] done processing
 79%|███████▉  | 89/113 [00:14<00:06,  3.80it/s]10:50:13 - cmdstanpy - INFO - Chain [1] start processing
10:50:13 - cmdstanpy - INFO - Chain [1] done processing
 80%|███████▉  | 90/113 [00:14<00:06,  3.50it/s]10:50:13 - cmdstanpy - INFO - Chain [1] start processing
10:50:13 - cmdstanpy - INFO - Chain [1] done processing
 81%|████████  | 91/113 [00:14<00:06,  3.53it/s]10:50:14 - cmdstanpy - INFO - Chain [1] start processing
10:50:14 - cmdstanpy - INFO - Chain [1] done processing
 81%|████████▏ | 92/113 [00:15<00:06,  3.46it/s]10:50:14 - cmdstanpy - INFO - Chain [1] start processing
10:50:14 - cmdstanpy - INFO - Chain [1] done processing
 82%|████████▏ | 93/113 [00:15<00:05,  3.58it/s]10:50:14 - cmdstanpy - INFO - Chain [1] start processing
10:50:14 - cmdstanpy - INFO - Chain [1] done processing
 83%|████████▎ | 94/113 [00:15<00:05,  3.59it/s]10:50:14 - cmdstanpy - INFO - Chain [1] start processing
10:50:15 - cmdstanpy - INFO - Chain [1] done processing
 84%|████████▍ | 95/113 [00:15<00:04,  3.67it/s]10:50:15 - cmdstanpy - INFO - Chain [1] start processing
10:50:15 - cmdstanpy - INFO - Chain [1] done processing
 85%|████████▍ | 96/113 [00:16<00:04,  3.62it/s]10:50:15 - cmdstanpy - INFO - Chain [1] start processing
10:50:15 - cmdstanpy - INFO - Chain [1] done processing
 86%|████████▌ | 97/113 [00:16<00:04,  3.54it/s]10:50:15 - cmdstanpy - INFO - Chain [1] start processing
10:50:15 - cmdstanpy - INFO - Chain [1] done processing
 87%|████████▋ | 98/113 [00:16<00:04,  3.60it/s]10:50:16 - cmdstanpy - INFO - Chain [1] start processing
10:50:16 - cmdstanpy - INFO - Chain [1] done processing
 88%|████████▊ | 99/113 [00:17<00:04,  3.48it/s]10:50:16 - cmdstanpy - INFO - Chain [1] start processing
10:50:16 - cmdstanpy - INFO - Chain [1] done processing
 88%|████████▊ | 100/113 [00:17<00:03,  3.56it/s]10:50:16 - cmdstanpy - INFO - Chain [1] start processing
10:50:16 - cmdstanpy - INFO - Chain [1] done processing
 89%|████████▉ | 101/113 [00:17<00:03,  3.42it/s]10:50:16 - cmdstanpy - INFO - Chain [1] start processing
10:50:17 - cmdstanpy - INFO - Chain [1] done processing
 90%|█████████ | 102/113 [00:17<00:03,  3.66it/s]10:50:17 - cmdstanpy - INFO - Chain [1] start processing
10:50:17 - cmdstanpy - INFO - Chain [1] done processing
 91%|█████████ | 103/113 [00:18<00:02,  3.85it/s]10:50:17 - cmdstanpy - INFO - Chain [1] start processing
10:50:17 - cmdstanpy - INFO - Chain [1] done processing
 92%|█████████▏| 104/113 [00:18<00:02,  3.63it/s]10:50:17 - cmdstanpy - INFO - Chain [1] start processing
10:50:17 - cmdstanpy - INFO - Chain [1] done processing
 93%|█████████▎| 105/113 [00:18<00:02,  3.74it/s]10:50:17 - cmdstanpy - INFO - Chain [1] start processing
10:50:18 - cmdstanpy - INFO - Chain [1] done processing
 94%|█████████▍| 106/113 [00:19<00:01,  3.70it/s]10:50:18 - cmdstanpy - INFO - Chain [1] start processing
10:50:18 - cmdstanpy - INFO - Chain [1] done processing
 95%|█████████▍| 107/113 [00:19<00:01,  3.69it/s]10:50:18 - cmdstanpy - INFO - Chain [1] start processing
10:50:18 - cmdstanpy - INFO - Chain [1] done processing
 96%|█████████▌| 108/113 [00:19<00:01,  3.35it/s]10:50:18 - cmdstanpy - INFO - Chain [1] start processing
10:50:18 - cmdstanpy - INFO - Chain [1] done processing
 96%|█████████▋| 109/113 [00:19<00:01,  3.40it/s]10:50:19 - cmdstanpy - INFO - Chain [1] start processing
10:50:19 - cmdstanpy - INFO - Chain [1] done processing
 97%|█████████▋| 110/113 [00:20<00:00,  3.26it/s]10:50:19 - cmdstanpy - INFO - Chain [1] start processing
10:50:19 - cmdstanpy - INFO - Chain [1] done processing
 98%|█████████▊| 111/113 [00:20<00:00,  3.10it/s]10:50:19 - cmdstanpy - INFO - Chain [1] start processing
10:50:20 - cmdstanpy - INFO - Chain [1] done processing
 99%|█████████▉| 112/113 [00:21<00:00,  2.89it/s]10:50:20 - cmdstanpy - INFO - Chain [1] start processing
10:50:20 - cmdstanpy - INFO - Chain [1] done processing
100%|██████████| 113/113 [00:21<00:00,  5.27it/s]

In [1]:
ans['COGS'] = forecast['yhat'].values

NameError: name 'forecast' is not defined

In [31]:
ans.to_csv("prophet_submission.csv", index=False)