In [15]:
import pandas as pd
import numpy as np

In [16]:
orders = pd.read_csv('../../orders.csv')
order_items = pd.read_csv('../../order_items.csv')
products = pd.read_csv('../../products.csv')
customers = pd.read_csv('../../customers.csv')
geography = pd.read_csv('../../geography.csv')

/var/folders/36/khn_y8zn7qqflczfpst8cbfc0000gn/T/ipykernel_44636/981946977.py:2: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  order_items = pd.read_csv('../../order_items.csv')

In [17]:
orders_detail = orders.merge(geography, on='zip', how='left').merge(order_items, on='order_id', how='left').merge(products, on='product_id', how='left')
orders_detail

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,city,region,...,discount_amount,promo_id,promo_id_2,product_name,category,segment,size,color,price,cogs
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search,Hanoi,East,...,0.0,NaN,NaN,VietMotion YY-09,GenZ,Trendy,S,red,1109.261061,1053.798008
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search,Phu Ly,East,...,0.0,NaN,NaN,SaigonFlex UC-74,Streetwear,Everyday,M,yellow,10426.571034,8987.704231
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct,Lao Cai,East,...,0.0,NaN,NaN,SaigonFlex UM-01,Streetwear,Balanced,S,green,11028.428695,10091.012256
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral,Son Tay,East,...,0.0,NaN,NaN,SaigonFlex UC-00,Streetwear,Everyday,XL,purple,10745.220588,9205.430478
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign,Uong Bi,East,...,0.0,NaN,NaN,UrbanVN RP-10,Outdoor,Activewear,XL,purple,1609.911509,1048.696357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714664,834372,2022-12-31,19490,33907,delivered,credit_card,mobile,email_campaign,Bac Ninh,East,...,0.0,NaN,NaN,SaigonFlex UC-55,Streetwear,Everyday,L,red,4598.817231,3100.062695
714665,834377,2022-12-31,73046,37091,delivered,credit_card,mobile,referral,Ha Long,East,...,0.0,NaN,NaN,UrbanVN UM-02,Streetwear,Balanced,XL,purple,5159.312851,3025.421056
714666,834387,2022-12-31,107723,80516,delivered,credit_card,mobile,email_campaign,Kon Tum,Central,...,0.0,NaN,NaN,VietMotion UE-05,Streetwear,Performance,XL,black,7365.661770,6671.816431
714667,834392,2022-12-31,139431,93510,delivered,paypal,desktop,direct,Ben Tre,West,...,0.0,NaN,NaN,MekongFit RS-03,Outdoor,Premium,XL,purple,4828.925117,4587.478861
714668,834397,2022-12-31,136302,95678,delivered,credit_card,tablet,organic_search,Bac Lieu,West,...,0.0,NaN,NaN,MekongFit RS-06,Outdoor,Premium,L,pink,4700.352036,4323.853838

In [18]:
orders_detail['order_date'] = pd.to_datetime(orders_detail['order_date'])

In [19]:
orders_detail['total_revenue'] = orders_detail['quantity'] * orders_detail['unit_price']
orders_detail['total_cogs'] = orders_detail['quantity'] * orders_detail['cogs']
orders_detail

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,city,region,...,promo_id_2,product_name,category,segment,size,color,price,cogs,total_revenue,total_cogs
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search,Hanoi,East,...,NaN,VietMotion YY-09,GenZ,Trendy,S,red,1109.261061,1053.798008,7967.54,7376.586059
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search,Phu Ly,East,...,NaN,SaigonFlex UC-74,Streetwear,Everyday,M,yellow,10426.571034,8987.704231,71163.75,62913.929616
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct,Lao Cai,East,...,NaN,SaigonFlex UM-01,Streetwear,Balanced,S,green,11028.428695,10091.012256,33660.99,30273.036767
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral,Son Tay,East,...,NaN,SaigonFlex UC-00,Streetwear,Everyday,XL,purple,10745.220588,9205.430478,53196.25,46027.152390
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign,Uong Bi,East,...,NaN,UrbanVN RP-10,Outdoor,Activewear,XL,purple,1609.911509,1048.696357,1597.84,1048.696357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714664,834372,2022-12-31,19490,33907,delivered,credit_card,mobile,email_campaign,Bac Ninh,East,...,NaN,SaigonFlex UC-55,Streetwear,Everyday,L,red,4598.817231,3100.062695,35791.36,24800.501564
714665,834377,2022-12-31,73046,37091,delivered,credit_card,mobile,referral,Ha Long,East,...,NaN,UrbanVN UM-02,Streetwear,Balanced,XL,purple,5159.312851,3025.421056,36755.53,21177.947390
714666,834387,2022-12-31,107723,80516,delivered,credit_card,mobile,email_campaign,Kon Tum,Central,...,NaN,VietMotion UE-05,Streetwear,Performance,XL,black,7365.661770,6671.816431,59112.48,53374.531451
714667,834392,2022-12-31,139431,93510,delivered,paypal,desktop,direct,Ben Tre,West,...,NaN,MekongFit RS-03,Outdoor,Premium,XL,purple,4828.925117,4587.478861,23836.65,22937.394304
714668,834397,2022-12-31,136302,95678,delivered,credit_card,tablet,organic_search,Bac Lieu,West,...,NaN,MekongFit RS-06,Outdoor,Premium,L,pink,4700.352036,4323.853838,4716.75,4323.853838

In [20]:
orders_detail.drop(columns=['quantity', 'unit_price','cogs'], inplace=True)

In [21]:
orders_detail

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,city,region,...,promo_id,promo_id_2,product_name,category,segment,size,color,price,total_revenue,total_cogs
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search,Hanoi,East,...,NaN,NaN,VietMotion YY-09,GenZ,Trendy,S,red,1109.261061,7967.54,7376.586059
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search,Phu Ly,East,...,NaN,NaN,SaigonFlex UC-74,Streetwear,Everyday,M,yellow,10426.571034,71163.75,62913.929616
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct,Lao Cai,East,...,NaN,NaN,SaigonFlex UM-01,Streetwear,Balanced,S,green,11028.428695,33660.99,30273.036767
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral,Son Tay,East,...,NaN,NaN,SaigonFlex UC-00,Streetwear,Everyday,XL,purple,10745.220588,53196.25,46027.152390
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign,Uong Bi,East,...,NaN,NaN,UrbanVN RP-10,Outdoor,Activewear,XL,purple,1609.911509,1597.84,1048.696357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714664,834372,2022-12-31,19490,33907,delivered,credit_card,mobile,email_campaign,Bac Ninh,East,...,NaN,NaN,SaigonFlex UC-55,Streetwear,Everyday,L,red,4598.817231,35791.36,24800.501564
714665,834377,2022-12-31,73046,37091,delivered,credit_card,mobile,referral,Ha Long,East,...,NaN,NaN,UrbanVN UM-02,Streetwear,Balanced,XL,purple,5159.312851,36755.53,21177.947390
714666,834387,2022-12-31,107723,80516,delivered,credit_card,mobile,email_campaign,Kon Tum,Central,...,NaN,NaN,VietMotion UE-05,Streetwear,Performance,XL,black,7365.661770,59112.48,53374.531451
714667,834392,2022-12-31,139431,93510,delivered,paypal,desktop,direct,Ben Tre,West,...,NaN,NaN,MekongFit RS-03,Outdoor,Premium,XL,purple,4828.925117,23836.65,22937.394304
714668,834397,2022-12-31,136302,95678,delivered,credit_card,tablet,organic_search,Bac Lieu,West,...,NaN,NaN,MekongFit RS-06,Outdoor,Premium,L,pink,4700.352036,4716.75,4323.853838

In [22]:
df = orders_detail.groupby(['order_date','city'])['total_revenue'].sum().reset_index()
df['total_cogs'] = orders_detail.groupby(['order_date','city'])['total_cogs'].sum().values
df

       order_date           city  total_revenue     total_cogs
0      2012-07-04      Bac Giang       81053.07   64922.655558
1      2012-07-04       Bac Lieu       42218.24   38219.800296
2      2012-07-04       Bac Ninh      165061.62  131300.067841
3      2012-07-04       Bien Hoa       74444.36   68096.731500
4      2012-07-04  Buon Ma Thuot       96028.33   70585.928461
...           ...            ...            ...            ...
144994 2022-12-31       Tra Vinh      131631.80  144801.288351
144995 2022-12-31        Tuy Hoa       45265.36   52545.533731
144996 2022-12-31       Viet Tri      183937.86  158076.566133
144997 2022-12-31      Vinh Long       48547.81   42537.308486
144998 2022-12-31       Vung Tau       60296.40   71782.720143

[144999 rows x 4 columns]

In [26]:
df[df['city'] == 'Ho Chi Minh City']

       order_date              city  total_revenue     total_cogs
52     2012-07-05  Ho Chi Minh City       86408.35   62603.339349
87     2012-07-06  Ho Chi Minh City       82749.19   77932.433339
151    2012-07-08  Ho Chi Minh City      119029.54   98417.117167
187    2012-07-09  Ho Chi Minh City      108424.84   75327.588778
226    2012-07-10  Ho Chi Minh City       44915.94   36783.426492
...           ...               ...            ...            ...
144652 2022-12-22  Ho Chi Minh City       76697.32   65313.851470
144753 2022-12-25  Ho Chi Minh City       47381.58   36648.657483
144786 2022-12-26  Ho Chi Minh City       34597.54   42249.416305
144864 2022-12-28  Ho Chi Minh City      109720.05  102041.540078
144977 2022-12-31  Ho Chi Minh City       71623.51   78953.281379

[3351 rows x 4 columns]

In [ ]:
# lấy danh sách city
cities = df['city'].unique()

# loop từng city
for city in cities:
    temp = df[df['city'] == city].copy()
    
    # set index
    temp = temp.set_index('order_date').asfreq('D').fillna(0)
    
    # lưu file
    temp.to_csv(f'daily_{city}.csv')